[package]
name = "venial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.36"

[dev-dependencies]
insta = "1.12.0"
quote = "1.0.15"
